### PR TITLE
feat: https://github.com/GetAlluo/alluo-protocol/issues/17

### PR DESCRIPTION
**Pull request by HarryTgerman**

### CODE REVIEW

**Comment by HarryTgerman** [comment]
just realized made some mistakes with decimals, can't have negative decimals! will work on tomorrow.

**Comment by 0xtuytuy** [comment]
Please make sure to write the test with hardhat as well.

**Comment by zayk00v** [comment]
Hi, thanks for your contribution and sorry for late response.
I dont think that it is what we wanted to see, probably the problem was in not very clear explanation. 
we are moving away from the current idea with claim, and what we wanted to see in this bounty is a complete change in the reward system. something like new algorithm that change ratio between alluoLp and stables.
Example: at the beginning user will get 100 alluoLp for 100 stables, but after a year he will get only 100 alluoLp for 108 stables, if interest was 8 whole year.
As i am writing it i get that it is even simpler than i though and then current implementation. So now if you will try console.log (DF) in update function in tests (like calling it every day) you will see how it gradually go from 100 to 108+, basically it is price(ratio) of alluoLp to stables. you need to calculate how much alluoLp you need to mint in deposit and burn in withdraw based on this growing ratio. it is pretty simple.
Two more things: first maybe we need change formula of updating DF so it will not go over 108 in one year and will grow linearly. Second you need prepare migration function so we can call it after upgrading, claim all rewards for users(probably we will input all users addresses manually), refresh DF and so on. And please also dont forget about tests. dont worry about exchange in tests or if you want you can see how we exchanging it now using curve Aave pool in deploy branch

**Comment by 0xtuytuy** [comment]
Please note that there are 2 people working on the same bounty
- #22 
- #21 

@HarryTgerman and @pentatonictritones it might be worth joining forces 🤲

**Comment by 0xtuytuy** [comment]
Work for the same bounty was submitted and approved here:
- https://github.com/GetAlluo/alluo-protocol/pull/22

Thank you for your work @HarryTgerman we invite you to review the work that was accepted and the rest of the bounties that are available.

**Pull request closed without merging**
